spring.application.name=grocery-backend
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://chavanprathamesh813_db_user:Chavan123@cluster0.uwicoiz.mongodb.net/grocery_db

# JWT
jwt.secret=your_super_secret_key_minimum_32_characters_long
jwt.expiration=86400000

# Mail (we'll add this later)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chavanprathamesh813@gmail.com
spring.mail.password=ecmlxobsotslrmoh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJwcmF0aGFtZXNoY2hhdmFuMzIwNUBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NzM4Mjc0ODMsImV4cCI6MTc3MzkxMzg4M30.sy9fD4s0EQnEHujN0GgMo2eqZB0jAgK8amfgQgizF24j5cCLo4KlkafEA2m6E7qK